
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
b8 a+32/3 b32/3 ab8/3 c+32/3 g8/3+32/3 b4 d8 g8 ab8 b8 b-8/3 c++16/3 a8 g8 f8 g8 a8
