
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
r8/3+32/3 eb+8/3+32/3+16/3 b8 r4 e+8 d+8 f+8 e+4 c+8 a16/3 g8/3 ab8 f8 eb+16/3 a-32/3 eb+16
