
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
f8 e8 d8/3 e8/3+32/3+16 f8 e16/3 g8/3 bb8 f8/3 ab-32/3 d++32/3 db8/3+32/3+16 bb8/3 e8 db8 g+8 a8 bb8 a16/3 ab-16/3
