
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
e16/3 g16/3 eb32/3 f8/3+32/3+16/3 e8 a-32/3 d32/3 a8/3 f8 g8 ab32/3 g32/3 e+8/3 b8 gb+16/3 c++8/3 a+4 bb+8 a+4 g+8
