
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
c8 r8 f8 g8 f16/3 db32/3 d32/3 db8/3 d8/3 g8 a8 e+8 eb+8 a8 g4 e8
