
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
r8/3+32/3 eb+8/3+32/3+16/3 b8 r4 e+8 d+8 c+8 b+32/3 e+8 b+32/3 e+8/3 b8 a16/3 b+8/3+32/3+16 ab16/3 f8 g8 d+16/3
