
(section (style swing))

(part (type chords))
NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC | NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC NC |
(part (type melody))
a32/3 c+8/3+32/3 d+8 f+8 e+8 d+8 e+8 c+8/3 g16/3 a8 b2+8 bb8 a8
